#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mkdir -p ~/.local/bin

bash "$DIR/bash/install"
bash "$DIR/i3/install"
bash "$DIR/git/install"
bash "$DIO/theme/install"
bash "$DIR/vim/install"
