#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ln -si "$DIR/vimrc" ~/.vimrc
mkdir -p ~/.vim/bundle
ln -si "$DIR/bundles.vim" ~/.vim/bundles.vim

if [ ! -d ~/.vim/bundle/vundle ]; then
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
  vim -u "$DIR/bundles.vim" +BundleInstall +qa
fi
