alias pm='yaourt --noconfirm'

alias sudo='sudo '
alias blink="ruby -e 'loop{$><<\"\r\x1b[#{31+($.+=1)%7}m#{ARGV[0] || \"BLINK\"}\";sleep 0.08}'"

# systemd aliases
alias start='sudo systemctl start'
alias stop='sudo systemctl stop'
alias restart='sudo systemctl restart'
alias enable='sudo systemctl enable'
alias disable='sudo systemctl disable'
alias status='sudo systemctl status'
alias journal='sudo journalctl -xn'

# git aliases
alias g='git'
alias gl='git log'
alias gs='git status'
alias gc='git commit'
alias ga='git add'
alias gd='git diff'
alias gp='git push'
alias gaa='git add --all -v'
alias gcm='git commit -m'
alias gcam='git commit --all -v -m'
